### ISSUE TITLE
Calling .say() with options makes the inner-SSML look like [object Object]

### ISSUE THREAD

**Issue by MaxwellPayne** [TheFuzzy/node-ssml#3]
Calling the .say() method with an options object instead of text makes the text show up as `[object Object]`. You can reproduce this by following an example in the README:
```javascript
ssmlDoc.say('The time now is ')
    .say({
        text: '01:59:59',
        intepretAs: 'telephone',
        format: 'hms24'
    })
    .toString()
```
This yields a `say-as` element that looks like:
```XML
<say-as intepret-as="telephone" format="hms24">[object Object]</say-as>
```

**Comment by TheFuzzy** [comment]
This bug stems from a requirement of mine that the library be able to accept a complex Object as the `text` argument, and call its `toString()` method as necessary.

I realize now that this decision was foolish, as developers can (and should) opt to call `toString()` themselves for the `text` argument. Thus, I'm disabling this unneeded 'feature'.

Thank you for the pull request, but this change will be better for the `say()` method.
